#!/usr/bin/env bash

docker network create monitoring \
	-d bridge \
	--scope local \
	--attachable \
	--label com.docker.compose.network=monitoring

echo "Set up monitoring service with domain name: "${1}

echo "DOMAIN="${1} > ./.env

docker-compose down && docker-compose up -d